services:
  backend:
    hostname: "backend"
    image: "ghcr.io/synkolbasyn/secunda:backend"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    expose:
      - "80"
    env_file:
      - "./.env"
    depends_on:
      - "postgresql"
    restart: "unless-stopped"

  frontend:
    hostname: "frontend"
    image: "ghcr.io/synkolbasyn/secunda:frontend"
    build:
      context: "./nginx/"
      dockerfile: "./Dockerfile"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "backend"
    restart: "unless-stopped"

  postgresql:
    hostname: "$POSTGRES_HOST"
    image: "postgres:latest"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - "./.env"
    shm_size: "1gb"
    restart: "unless-stopped"
