name: Build

on:
  workflow_run:
    workflows: [Lint]
    types: [completed]
    branches: [main, dev]

jobs:
  frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./nginx/
          file: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/synkolbasyn/secunda:frontend

  backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/synkolbasyn/secunda:backend
